### ISSUE TITLE
ipchange

### ISSUE THREAD

**Issue by phoolish** [TheSerapher/chef-vsftpd#12]
I have an interesting problem.  Our IP changed during a reboot.  When vsftpd tried to start during boot it silently failed.  The Chef run also fails because the IP in the conf file has not been updated and the service gets defined before the conf file.  Our temporary solution was to add a service resource to our wrapper cookbook and define ignore_failure.  I don't like this approach at all.  An alternative might be to add no action to the original service resource declaration and then a second service resource post config to check for enable & start.  This should still allow for template changes to notify a delayed restart at the end of the run.

**Comment by TheSerapher** [comment]
Yes that is indeed an issue. I would assume your solution will work just fine. It doesn't really matter when the service is enabled/started after all.

Will do this and try it out.

**Comment by phoolish** [comment]
@TheSerapher I think #10 solves this problem.

**Comment by TheSerapher** [comment]
Woupsie .. Merged it, can you try it out?

**Comment by phoolish** [comment]
Worked perfectly on test-kitchen and on prod.  Thanks for the quick turn around!

**Comment by TheSerapher** [comment]
My pleasure, cool to see people actually use this ;-) It's one of my earliest works!

**Comment by phoolish** [comment]
Legacy apps ;)

**Comment by TheSerapher** [comment]
They don't require a lot of maintenance, but if I do get a ticket why not fix it, right? :beetle:
